POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWVlZWZlMzBjYTBhNjgxMGUwYmY1ZDM1IiwiaWF0IjoxNTkzOTM3MzM3fQ.u7ev9WFW2DsLszPpvDHxDbNMZrRkPCTWixnvktkwGcg

{
    "title": "This is Function Calls",
    "author": "Marius Schulz",
    "url": "https://egghead.io/lessons/javascript-this-in-function-calls"
}